### ISSUE TITLE
HorizontalPageLayoutManager崩溃

### ISSUE THREAD

**Issue by may7be** [zhuguohui/HorizontalPage#15]
当只有一页，左右使劲滑动多次，必然会崩溃。
HorizontalPageLayoutManager执行到recyclerAndFillItems()的Rect.intersects(diaplagRect, childRect)时会报空指针异常。
作者能看看为什么吗？

**Comment by AsyncHope** [comment]
java.lang.NullPointerException: Layout parameters cannot be null
        at android.view.View.setLayoutParams(View.java:15251)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5605)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
        at xxxxxx.HorizontalPageLayoutManager.onLayoutChildren(HorizontalPageLayoutManager.java:110)
HorizontalPageLayoutManager  View view = recycler.getViewForPosition(index); 报空指针
